### ISSUE TITLE
c00000bb UNKNOWN

### ISSUE THREAD

**Issue by unextro** [yoichiro/chromeos-filesystem-cifs#113]
Hello Yoichiro,

![screenshot 2015-09-08 at 17 06 16 - edited](https://cloud.githubusercontent.com/assets/13996981/9762997/62ba24c4-5707-11e5-8d4a-08f878962d9e.png)

![screenshot 2015-09-08 at 14](https://cloud.githubusercontent.com/assets/13996981/9762999/68fe2452-5707-11e5-9790-eea6cb8814b2.png)

BTW, the same settings were throwing error described in #69 before the latest version...

Let me know if there's anything else I can do to identify the problem... Thanks for your work on this extension!

**Comment by mates52472** [comment]
Yep, got the same issue... can someone advise, please ?? :)

**Comment by yoichiro** [comment]
@unextro @mates52472 I just released a new version 2.1.1. The previous version included a bug which a wrong path specified (\srvsvc). I guess that you can access to your server with the latest version. It would be great if you can do test again.

**Comment by unextro** [comment]
@yoichiro Still the same error message after the app update... :/

**Comment by yoichiro** [comment]
@unextro I see... It would be great if you can post the debug log again after changing the debug log level to "Trace" by clicking the gear icon on the bottom of the left on the login panel. I want to know the command when the error occurred.

**Comment by yoichiro** [comment]
@unextro Ping.

**Comment by unextro** [comment]
Hi @yoichiro, I've read your response, but the problem appears inside our corporate network and I won't be in the office until Tuesday (it's national holiday in Czech Republic). Expect the logs tomorrow. :) Thanks for your help

**Comment by unextro** [comment]
Hello again @yoichiro, I've sent the log file directly to your e-mail address since it contains corporate credentials etc.

**Comment by unextro** [comment]
Hi @yoichiro, did you receive the log? Is there anything else I can do?

**Comment by yoichiro** [comment]
@unextro I'm sorry for delay. I'm checking the log you sent to me. Just a moment.

**Comment by yoichiro** [comment]
@unextro Hmm... The error code "C00000BB" means "STATUS_NOT_SUPPORTED". That is, your server rejected the QueryInfoRequest which my app sent, because the server doesn't support the command, I think. So, when I read the log, you tried to access to the shared resource named "msmid$". Is the "msmid$" resource for file sharing?

**Comment by unextro** [comment]
@yoichiro The resource is definitely for file sharing. It contains some files. The folder is accessible from Windows without problem. Even your extension says mounted successfully and then gives the C00000BB error later...

**Comment by yoichiro** [comment]
@unextro I would like to confirm one thing. Can you reproduce this issue with the latest version 2.3.1?

**Comment by BDUGert** [comment]
Same problem at my company. I send you a log directly because of the confidential information in the file. Latest version (2.3.1) has been used. Accessing a native Windows server works well. 
Trying to access a NetApp Cifs share (without a Windows server) returns the c00000bb error. Mounting the volume returns no error.

**Comment by unextro** [comment]
I can confirm 2.3.1 behaves the same as previous version(s). Mounts successfully and then gives the c00000bb.

**Comment by unextro** [comment]
Funnily enough, I just found out that the share we're trying to access is also on the NetApp share.

**Comment by yoichiro** [comment]
@unextro @BDUGert @mates52472 I found a bug regarding authentication. I have already released a new version 2.4.0 including code to fix the issue. See the following post for more detail: https://plus.google.com/u/0/+YoichiroTanaka/posts/EEJyicfnSqK

I'm not sure that the new version can solve this issue, but could you confirm whether or not the new version works on your environment?

**Comment by BDUGert** [comment]
I tested the new version but I got the same c00000bb error when trying to mount the system.
I'll send you the log file.

**Comment by unextro** [comment]
Yep, the bug still remains. We have a meeting with our NetApp admins planned for tomorrow so hopefully we'll get some log from the NAS as well...

**Comment by yoichiro** [comment]
Hmm... Currently, I don't have any idea to fix the error...

@unextro @mates52472 @BDUGert I want to know the corrent packets to communicate between your client and the target server. It would be great if you can capture the packets by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-capture-packets-with-Wireshark

**Comment by yoichiro** [comment]
@unextro @mates52472 @BDUGert Then, I was finding this reason. Well, my app is using a "FileAllInformation" sub command in a QueryInfoRequest command to fetch information of the target file: https://msdn.microsoft.com/en-us/library/cc232117.aspx However, I guess that your NetApp server doesn't support the sub command... Probably, I can check about that (if there is no FileAllInformation sub command in the captured packets, your client tried to avoid using un-supported sub command). Or, could you ask a person in charge of your NetApp about whether or not the NetApp server supports the sub command?

**Comment by yoichiro** [comment]
Probably, this is the cause of this problem... https://msdn.microsoft.com/en-us/library/cc232099.aspx

**Comment by yoichiro** [comment]
I posted my opinion against this issue on G+: https://plus.google.com/u/0/+YoichiroTanaka/posts/JPK7AahUDRj

**Comment by unextro** [comment]
I can happily confirm that the 2.5.0 solves the issue for us! Many thanks, @yoichiro...

**Comment by yoichiro** [comment]
@unextro My pleasure. You can close this issue. Thank you for the feedback!

**Comment by BDUGert** [comment]
Problem is solved, many thanks @yoichiro

**Comment by yoichiro** [comment]
@BDUGert My pleasure.
