### ISSUE TITLE
NT Status Access Denied (Windows 10 Pro)

### ISSUE THREAD

**Issue by robertstrom** [yoichiro/chromeos-filesystem-cifs#149]
Hello,

I've been trying to use your app to connect to my Windows 10 system (Windows 10 Pro not in a domain) and keep getting the NT STATUS ACCESS DENIED message if I try logging in as USER NAME = Robert. If I try logging in as 192.168.0.198\Robert I get the message NT STATUS LOGON FAILURE.

Where is the log located so that I can send it to you?

Thanks,

Robert

**Comment by yoichiro** [comment]
@robertstrom It would be great if you post a comment attached the log file or send an email to yoichiro[at]eisbahn.jp.

**Comment by robertstrom** [comment]
I'm happy to post the logs. Where do I find them?

**Comment by yoichiro** [comment]
@robertstrom Oh, I'm sorry. You can collect a log with the following steps: https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools
Please send the log file via email to me.

**Comment by yoichiro** [comment]
@robertstrom Yesterday, I tried to access to my Win10 (not use Domain auth) from my app. The error code was NT_STATUS_INVALD_PARAMETER, not NT_LOGIN_FAILURE and NT_STATUS_ACCESS_DENIED.

**Comment by yoichiro** [comment]
I found some differences of the IoctlRequest content like the following:
- Credits requested: Success:256, Failure:1
- Max Xmit Frag: Success:65535, Failure:4280
- Max Recv Frag: Success:65535, Failure:4280

**Comment by robertstrom** [comment]
Sorry that it's taken so long to get back to you ... I have not gotten any email notifications that this thread was updated (not sure that whether I should or not) and I just saw this when I happened to check up on the issue (I haven't been @ home to use my Chromebook to connect to my Windows 10 system).

I have gone to the extension page and looked for the "background page" link and there is none for version 2.6.1 of the application (which as far as I can tell is the current version). Your example is shown for your Dropbox application, not the "File System for Windows" application.

So ... my question is ... how do I collect the logs for the "File System for Windows" application?

Thanks,

Robert

**Comment by yoichiro** [comment]
@robertstrom At least, I found some problems regarding Win10. Currently, I'm testing a new version to fix these problems. The pull request has the modifications to fix the problems: #156. Anyway, I think that you don't need to provide logs to me right now.

**Comment by yoichiro** [comment]
@robertstrom I have released the new version 2.6.2 including code to fix this issue. Could you confirm whether or not you can reproduce this issue on your environment?

**Comment by robertstrom** [comment]
@yoichiro - I uninstalled and reinstalled the app just to be sure ... I am still getting the NT_STATUS_ACCESS_DENIED error

**Comment by yoichiro** [comment]
@robertstrom Really? Well, I need a debug log output on your environment. https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools In this page, there are some images of File System for Dropbox, but you can do the same way to collect the logs of File System for Windows.

**Comment by robertstrom** [comment]
@yoichiro This is the first chance that I've had to get the logs. One note with regards to your instructions to collect the logs ... I don't believe that it mentions that you need to check the Developer mode box in order to see the background page.

Logs should be attached.

[rstrom_file_system_for_windows.log.txt](https://github.com/yoichiro/chromeos-filesystem-cifs/files/52701/rstrom_file_system_for_windows.log.txt)

**Comment by robertstrom** [comment]
@yoichiro - Just tried to mount my Win10 file system again and I'm getting the same error messages / not able to connect. Wondering if the logs gave you the info that you needed.

**Comment by robertstrom** [comment]
How do I tell what version of the APP is installed on my system / does it update automatically?

Thanks!

**Comment by robertstrom** [comment]
@yoichiro - Here's an update for you on inability to access / mount remote file systems. You may, or may not be aware of this so I figured I'd pass it along just in case.

While @ work today I connected my Chromebook to the corp wireless and attempted to connect to my Windows 7 laptop which is a member of our AD domain. I entered the IP address, the user name, password, domain, and the C$ admin share and I was connected. SUCCESS ... the first time that I have been able to get the application to work.

Then I tried to connect to another machine on the network, a Server 2012 domain controller (I have a logon that allows me to connect ... I tested from my Windows 7 system just to be 100% sure)  and was not able to. I got the same error messages that I got when trying to connect to my Windows 10 machine @ home (not a member of a domain). The varying error messages depended on whether or not I was using the correct password (I purposely entered the wrong password to see if the behavior would be different).

One other bit of information to pass along to you ... I have a Macbook Pro running OSX 10.11.2 and I am able to connect to shares on my Windows 10 system without issue.

HTH,

Robert
