### ISSUE TITLE
Connot logon on my server windows 2003/2012 domain

### ISSUE THREAD

**Issue by snoopyski** [yoichiro/chromeos-filesystem-cifs#150]
Hello,

I try a lots of configuration but still not able to login on my Windows Domain Server 2003 or 2012.

See the attached file log.

Tks,

Snoopyski !
[Snoopyski.log.txt](https://github.com/yoichiro/chromeos-filesystem-cifs/files/33012/Snoopyski.log.txt)

**Comment by yoichiro** [comment]
@snoopyski Thank you for the reporting. I'm testing a new version to fix this problem now. #156.

**Comment by yoichiro** [comment]
@snoopyski I have released the new version 2.6.2 including code to fix this issue. Could you confirm whether or not you can reproduce this issue on your environment with the new version?

**Comment by snoopyski** [comment]
Hello,

I try the lest version and still no luck ! Not working :-/

Stéphane Gauvin,
Président | Consultant
Tel. 450.536.2154
Cell. 514.808.2535
_SERVICE INFORMATIQUE SG_
sgauvin@serviceinfosg.com

2015-11-25 5:24 GMT-05:00 Yoichiro Tanaka notifications@github.com:

**Comment by yoichiro** [comment]
@snoopyski Could you provide me the debug log collected by the following steps again?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by snoopyski** [comment]
Hello,

There is an update... Same error :

Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_:

> 1, channelSequence_: 22…}
> background.js:6524 Asn1Obj {tag_: 161, value_: null, children_: Array[1]}
> background.js:6531 Response OID = 1.3.6.1.4.1.311.2.2.10
> background.js:6531 NTLMSSP_NEGOTIATE_UNICODE: true
> background.js:6531 NTLMSSP_NEGOTIATE_OEM: false
> background.js:6531 NTLMSSP_REQUEST_TARGET: true
> background.js:6531 NTLMSSP_NEGOTIATE_SIGN: true
> background.js:6531 NTLMSSP_NEGOTIATE_SEAL: false
> background.js:6531 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
> background.js:6531 NTLMSSP_NEGOTIATE_LM_KEY: false
> background.js:6531 NTLMSSP_NEGOTIATE_NETWARE: false
> background.js:6531 NTLMSSP_NEGOTIATE_NTLM: true
> background.js:6531 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
> background.js:6531 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
> background.js:6531 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
> background.js:6531 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: true
> background.js:6531 NTLMSSP_TARGET_TYPE_DOMAIN: true
> background.js:6531 NTLMSSP_TARGET_TYPE_SERVER: false
> background.js:6531 NTLMSSP_TARGET_TYPE_SHARE: false
> background.js:6531 NTLMSSP_NEGOTIATE_NTLM2_KEY: true
> background.js:6531 NTLMSSP_REQUEST_INIT_RESPONSE: false
> background.js:6531 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
> background.js:6531 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
> background.js:6531 NTLMSSP_NEGOTIATE_TARGET_INFO: true
> background.js:6531 NTLMSSP_NEGOTIATE_128: true
> background.js:6531 NTLMSSP_NEGOTIATE_KEY_EXCH: false
> background.js:6531 NTLMSSP_NEGOTIATE_56: false
> background.js:6531 Use LMv2 and NTLMv2 because LMCompatibilityLevel=5
> background.js:6524 Header {types_: Types, protocol_: "SMB",
> structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
> background.js:6524 SessionSetupRequest {types_: Types, flags_: 0,
> securityMode_: 1, capabilities_: 1, channel_: 0…}
> background.js:6524 Packet {types_: Types, data_: ArrayBuffer, dataLength_:
> 492, packetHelper_: PacketHelper}
> background.js:6517 writePacket
> background.js:6524 FE53 4D42 4000 0100 0000 0000 0100 0100  .SMB@
> ...........
> 0000 0000 0000 0000 0300 0000 0000 0000  ................
> A0D2 0000 0000 0000 810D 00FC 1B80 0000  ................
> 0000 0000 0000 0000 0000 0000 0000 0000  ................
> 1900 0001 0100 0000 0000 0000 5800 9401  ............X...
> 0000 0000 0000 0000 A182 0190 3082 018C  ............0...
> A282 0188 0482 0184 4E54 4C4D 5353 5000  ........NTLMSSP.
> 0300 0000 1800 1800 4000 0000 EA00 EA00  ........@.......
> 5800 0000 1600 1600 4201 0000 1C00 1C00  X.......B.......
> 5801 0000 1000 1000 7401 0000 0000 0000  X.......t.......
> 0000 0000 0102 0000 1AFC A7AE 8FE0 5EA9  ..............^.
> 1EBB 85A2 DBB2 9A7A AF49 5B96 E576 AB96  .......z.I[..v..
> F531 888A 215F FD94 FE95 9832 5092 8BFF  .1..!_.....2P...
> 0101 0000 0000 0000 10FA 9729 1439 D101  ...........).9..
> 8A88 2AE7 EF07 0000 0000 0000 0200 1600  ..*.............
> 4400 5200 4100 5000 4500 4100 5500 3200  D.R.A.P.E.A.U.2.
> 3000 3000 3000 0100 0C00 4D00 4100 4900  0.0.0.....M.A.I.
> 5400 5200 4500 0400 2200 4400 7200 6100  T.R.E...".D.r.a.
> 7000 6500 6100 7500 3200 3000 3000 3000  p.e.a.u.2.0.0.0.
> 2E00 6C00 6F00 6300 6100 6C00 0300 3000  ..l.o.c.a.l...0.
> 4D00 4100 4900 5400 5200 4500 2E00 4400  M.A.I.T.R.E...D.
> 7200 6100 7000 6500 6100 7500 3200 3000  r.a.p.e.a.u.2.0.
> 3000 3000 2E00 6C00 6F00 6300 6100 6C00  0.0...l.o.c.a.l.
> 0500 2200 4400 7200 6100 7000 6500 6100  ..".D.r.a.p.e.a.
> 7500 3200 3000 3000 3000 2E00 6C00 6F00  u.2.0.0.0...l.o.
> 6300 6100 6C00 0700 0800 90E7 355A 1339  c.a.l.......5Z.9
> D101 0000 0000 0000 0000 4400 5200 4100  ..........D.R.A.
> 5000 4500 4100 5500 3200 3000 3000 3000  P.E.A.U.2.0.0.0.
> 4100 6400 6D00 6900 6E00 6900 7300 7400  A.d.m.i.n.i.s.t.
> 7200 6100 7400 6500 7500 7200 4600 5300  r.a.t.e.u.r.F.S.
> 5000 5F00 4300 4900 4600 5300  P._.C.I.F.S.
> background.js:6517 readPacket
> background.js:6517 _readPacketSize
> background.js:6517 _readPacketSize - 2
> background.js:6517 readPacket: 81
> background.js:6524 FE53 4D42 4000 0100 0000 0000 0100 0100  .SMB@
> ...........
> 0900 0000 0000 0000 0300 0000 0000 0000  ................
> A0D2 0000 0000 0000 810D 00FC 1B80 0000  ................
> BABF EE98 31EF A6FF F823 1F17 38AC E5A3  ....1....#..8...
> 0900 0000 4800 0900 A107 3005 A003 0A01  ....H.....0.....
> 00 .
> background.js:6524 Asn1Obj {tag_: 161, value_: null, children_: Array[1]}
> background.js:6517 Client#getSharedResourceList
> background.js:6524 Header {types_: Types, protocol_: "SMB",
> structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
> background.js:6524 TreeConnectRequest {types_: Types, path_:
> "\192.168.1.5\IPC$"}
> background.js:6524 Packet {types_: Types, data_: ArrayBuffer, dataLength_:
> 108, packetHelper_: PacketHelper}
> background.js:6517 writePacket
> background.js:6524 FE53 4D42 4000 0100 0000 0000 0300 0100  .SMB@
> ...........
> 0000 0000 0000 0000 0400 0000 0000 0000  ................
> A0D2 0000 0000 0000 810D 00FC 1B80 0000  ................
> 0000 0000 0000 0000 0000 0000 0000 0000  ................
> 0900 0000 4800 2400 5C00 5C00 3100 3900  ....H.$...1.9.
> 3200 2E00 3100 3600 3800 2E00 3100 2E00  2...1.6.8...1...
> 3500 5C00 4900 5000 4300 2400  5..I.P.C.$.
> background.js:6517 readPacket
> background.js:6517 _readPacketSize
> background.js:6517 _readPacketSize - 2
> background.js:6517 readPacket: 73
> background.js:6524 FE53 4D42 4000 0100 2200 00C0 0300 0100  .SMB@
> ...".......
> 0100 0000 0000 0000 0400 0000 0000 0000  ................
> A0D2 0000 0000 0000 810D 00FC 1B80 0000  ................
> 0000 0000 0000 0000 0000 0000 0000 0000  ................
> 0900 0000 0000 0000 5C ........\
> background.js:16877 c0000022: NT_STATUS_ACCESS_DENIED

Stéphane Gauvin,
Président | Consultant
Tel. 450.536.2154
Cell. 514.808.2535
_SERVICE INFORMATIQUE SG_
sgauvin@serviceinfosg.com

2015-12-01 7:44 GMT-05:00 Stéphane Gauvin sgauvin@serviceinfosg.com:

**Comment by dougwantstoknow** [comment]
Has anyone figured this out? I am experiencing the same issue, NT_STATUS_LOGON_FAILURE trying to connect to a Windows 7 share and a Server 2012 share.  

One strange thing I see is on the Mount a new Windows file server diaglog box.  Once I enter all the information and click KEEP, on the left window I see the IP address and port of the server and then beneath that in parenthesis, I see my authentication listed as domain@username instead of username@domain.  Is that right?

From what I can see on these posts, everybody is sending in logs and then there is no response.  Can anyone help?

Thanks
