### ISSUE TITLE
unable to mount linux hosted samba share

### ISSUE THREAD

**Issue by leonardtj** [yoichiro/chromeos-filesystem-cifs#25]
I have a smb share hosted on ubuntu server when trying to mount I get error 327681. my other shares hosted on windows all work both port 139 and 445 are open and the server doesn't require any login credentials.

**Comment by yoichiro** [comment]
@leonardtj I have just released the new version 1.1.2. Could you confirm whether this issue occurs again using the 1.1.2?

**Comment by leonardtj** [comment]
I currently have 1.1.3 and it still won't connect to that share I still get
the same error . please let me know if there is any additional info I can
provide or anything you would like to to try to help you resolve this bug.

[image: --]
Troy Leonard
[image: http://]about.me/leonardtj
http://about.me/leonardtj?promo=email_sig
 Follow me on Google+ https://plus.google.com/+TroyLeonard/
https://www.facebook.com/leonardtjand Twitter: @leonardtj
http://twitter.com/#%21/Leonardtj

**Comment by yoichiro** [comment]
@leonardtj Could you confirm the debug console output? Probably, some error occurrd at the time, I guess. You can confirm the output by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@leonardtj I close this issue, because you didn't provide enough information to me. You can reopen this issue when you provide some information by the steps above. Thank you for the reporting.
