### ISSUE TITLE
Support Domain Authentication

### ISSUE THREAD

**Issue by yoichiro** [yoichiro/chromeos-filesystem-cifs#28]
As the title. If you want this support, feel free to leave your comment here.

**Comment by AndreyLavrov** [comment]
The possibility to mount a file folder by a domain account is very important.
In real life no one use a file share by a local user account (especially in enterprises with established Active Directory).

**Comment by AndreyLavrov** [comment]
I wish to be as clear as possible and improve a feature request description.
It is important to implement authentication by domain user account (OpenLDAP and Active Directory) in this application. This is open an posibility to use the app in small companies (aka SMB) without changes in windows infrastructure.
A possibility to connect to a real enterprise folder (DFS) is more valuable but stay out of the scope of this application. I think many administrators will be very happy if someone write a DFS provider for FSP on Chromebook. This (DFS) app will make a chromebook a real enterprise client for corporations.
P.S. Short description of DFS possibilities: 
http://www.mcmcse.com/microsoft/guides/70-411/dfs.shtml

**Comment by VitaZalud** [comment]
I vote for this feature. From admin point of view it will be much easier to manage access to the shared folders through domain administration.

**Comment by yoichiro** [comment]
I just investigated about NT Domain and Active Directory Domain a bit. I cannot understand about ADC and Kerberos yet, but I understood that my application should send the Domain Name to the SMB server within the NTLM Response (currently, "?" is specified as the Domain Name), then the SMB server will delegate the authentication to the Domain Controller server, if the SMB server joined to the Domain as the Domain member. If this is correct, I will implement the feature (UI to fill in the Domain Name, and including the name to the NTLM Response). I guess that, at least, my application will be able to support NT Domain...

**Comment by AndreyLavrov** [comment]
Standalone client can authenticate on a domain member by NTLM or Kerberos protocols in theory. In a real world a standalone client use NTLM v2 protocol only because implementation of Kerberos protocol on Windows member server require a ticket (TGT) from the client (unfortunately  a standalone client has no TGT from a domain controller) and NTLM v1 protocol was disabled by default since Windows 2008 R2.

**Comment by AndreyLavrov** [comment]
Kerberos protocol was implemented in Chrome many years ago and works fine in Windows,  Mac and Linux versions. However, Kerberos protocol was disabled by default in Chrome OS. I think that your should carefully understand the meanings of this design decision therefore you should talk with Chromium project leaders about this question definitely.
If you decide to implement Kerberos protocol on Chromebook then I think it could be a distinct extension with an "SSO" name (Auth API) for Chromebook. This extension (SSO) may implement a Kerberos protocol for any user directory (at least OpenLDAP and Active Directory) as well as a "Join Domain" procedure for those directories like was implemented in Mac Directory Utility (without remote management capabilities).
After that you might develop "DFS" and "NFS" Chrome Apps for FSP that use SSO extension (Auth API) internally.

P.S. I think expansion Chromebook capabilities to Universal Client conception is a great possibility but I think implementations should be scoped to files management and users profiles only. Those capabilities allows people be free from vendor software chain and be able to migrate between clouds as easy as possible.

**Comment by yoichiro** [comment]
@AndreyLavrov Thank you for the advices! Well, if I want to support the Windows Domain authentication against the standalone-client (not the domain member), is the following code correct?

https://github.com/yoichiro/chromeos-filesystem-cifs/pull/49/files#diff-b05ec7768eb22dcf99690df98cbc73c0R66

In the current version, LMv2 Hash and NTLMv2 Hash have a "?" fixed character as the Domain name.  But, in the code above, the Domain name a user fills in will be set into the LMv2 and NTLMv2 Hash. I guess that when the SMB server receives the Type3 message including these Hash, the SMB server communicates to the Domain Controller for the authentication.

How do you think about above modification? Could you review the diff?

Sorry, I don't have any Windows Domain environment, therefore, I cannot test my code...

**Comment by AndreyLavrov** [comment]
I have tested SMB ver.1.2.0 with domain account credentials.
SMB/CIFS application can mount folders on the following OSes:
1) Windows Server 2008 R2 (EE SP1 x64) (domain member)
2) Windows Server 2012 R2 (DE) (domain member)

Account type:
Domain user (standard user account)

Domain type:
Active Directory (Forest level: Windows 2008 R2)

![mount](https://cloud.githubusercontent.com/assets/12710354/8089221/36cd9516-0faf-11e5-8718-04b68b6c736c.png)

**Comment by bjkluft** [comment]
Where do I find/install this version 1.2.0?
I have the stable ChromeOS version 43.0.2357.81

**Comment by yoichiro** [comment]
@AndreyLavrov Thank you for your cooperation! It seems that the version 1.2.0 can work on your domain environment. For example, if you don't fill in the domain name on the login dialog, does the mounting fail? If yes, I guess that the 1.2.0 could have an ability to mount the server which the domain authentication is necessary...

**Comment by yoichiro** [comment]
@bjkluft If you want to test the 1.2.0, you need to download the branch named "support_domain_authentication" as zip file to your Chromebook:
1. Download Zip file: http://github.com/yoichiro/chromeos-filesystem-cifs/archive/support_domain_authentication.zip to your Chromebook.
2. Extract the zip file.
3. Open the page: chrome://extensions/
4. Check the "Develop mode" checkbox.
5. Load the unpackaged extension: [your extracted directory]/app

**Comment by bjkluft** [comment]
Hi,

I just downloaded the zip and tried to install but I get the following error:

Failed to load extension from: ~/Downloads/chromeos-filesystem-cifs-support_domain_authentication/app
Could not load background script 'bower_components/cryptojslib/components/core.js'.

What to do?

**Comment by yoichiro** [comment]
@bjkluft Sorry, I forgot that the building process is necessary...

**Comment by AndreyLavrov** [comment]
I have tested SMB ver.1.2.0 with local user account and described results here:
https://github.com/yoichiro/chromeos-filesystem-cifs/issues/50

**Comment by yoichiro** [comment]
@AndreyLavrov I'm just reading #50. Big thanks! I intend to confirm the #50 issue soon.

**Comment by yoichiro** [comment]
I have just released the new version 1.2.0 including supporting Domain authentication with NTLMv2 authentication. If you have some problem after updating to 1.2.0 and trying to logon to your server with the domain auth, feel free to reopen this issue and leave a comment of the problem here.

**Comment by bjkluft** [comment]
Hello Yoichiro,

I don't know what I'm doing wrong but I still can't mount to my windows server. I get the following error:
2147483653: UNKNOWN with the following settings:
![screenshot 2015-06-13 at 9 31 15 am](https://cloud.githubusercontent.com/assets/12735834/8143473/f7e8fdb6-11ae-11e5-8a95-e05b3c5abcc3.png)

Can somebody help me with this? Still getting the errors....

**Comment by deongrobler1980** [comment]
Hi, we are having no luck connecting to a network file share on a winds server with this app from a pc, running chromium os. Seems like the app is trying to connect with NTLM v1 authentication.
The error we are getting is:
c000006d  NT_STATUS_LOGON_FAILURE
We have tried creating a local account on the file server and continue to receive the same error...?
How can you access the logs, which you can set the level for in the settings option of this app?

Deon
