### ISSUE TITLE
Files.app failed to mount a file system

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#32]
Steps to reproduce:
1) Install SMB app
2) Launch SMB app
3) Keep settings and set folder properties
4) Press a "MOUNT" button in a SMB app

Picture below was captured after a click on the MOUNT button.
Top-Right: Files.app console 
Bottom-Right: SMB console
![smb - after press mount](https://cloud.githubusercontent.com/assets/12710354/8006695/b514451a-0b9e-11e5-87f4-8b5193d88c1d.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Which version is the ChromeOS you are using?

**Comment by hvdwolf** [comment]
Hi,

First: Thanks for this initiative. Great.

I add to this issue as I think I have the same issue. The system is a Western Digital Worldbook. I can connect from Linux and Windows without problem.

SMB app: 1.1.5
System: Toshiba Chromebook 2
ChromeOS:
Versie 43.0.2357.81 (64-bit)
Platform 6946.55.0 (Official Build) stable-channel swanky
Firmware Google_Swanky.5216.238.5

Debug error:
NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6170 NTLMSSP_NEGOTIATE_OEM: false
background.js:6170 NTLMSSP_REQUEST_TARGET: true
background.js:6170 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6170 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6170 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6170 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6170 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6170 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6170 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6170 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6170 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6170 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6170 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6170 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6170 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6170 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6170 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6170 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6170 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6170 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6170 NTLMSSP_NEGOTIATE_128: true
background.js:6170 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6170 NTLMSSP_NEGOTIATE_56: false

**Comment by yoichiro** [comment]
@hvdwolf @AndreyLavrov Hmm... Both reports doesn't have the eough information to solve the problem... Change the log level to trace by clicking the gear icon, and get the log output of the Console tab of the DevTools. Then, put the log here.

**Comment by hvdwolf** [comment]
Sorry, but I can't find that trace level. I do find a setting for "Record heap allocation stack traces" under the Profiler but it doesn't generate extra information.

**Comment by yoichiro** [comment]
@hvdwolf I just released the new version 1.1.6. In this version, I deleted a UI to change the log level, that is, the log output should be displayed as trace level. Could you confirm the output again?

**Comment by yoichiro** [comment]
@hvdwolf @AndreyLavrov Probably, I could reproduce your situation. I just released a new version 1.1.8 to fix this issue. Could you confirm whether the new version works on your environment or not?

**Comment by hvdwolf** [comment]
Hi, I just checked with your 1.1.8 version.

Unfortunately it still doesn't work. See below. I removed the password.

Object {type: "getSharedResources", serverName: "192.168.144.140", serverPort: "445", username: "pohd", password: "xxxxxx"}
background.js:6157 Client#login
background.js:6157 connect
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 127
background.js:6171 CAP_EXTENDED_SECURITY: true
background.js:6171 CAP_COMPRESSED_DATA: false
background.js:6171 CAP_BULK_TRANSFER: false
background.js:6171 CAP_UNIX: true
background.js:6171 CAP_LARGE_WRITEX: true
background.js:6171 CAP_LARGE_READX: true
background.js:6171 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6171 CAP_DFS: true
background.js:6171 CAP_NT_FIND: true
background.js:6171 CAP_LOCK_AND_READ: true
background.js:6171 CAP_LEVEL_II_OPLOCKS: true
background.js:6171 CAP_STATUS32: true
background.js:6171 CAP_RPC_REMOTE_APIS: true
background.js:6171 CAP_NT_SMBS: true
background.js:6171 CAP_LARGE_FILES: true
background.js:6171 CAP_UNICODE: true
background.js:6171 CAP_MPX_MODE: false
background.js:6171 CAP_RAW_MODE: true
background.js:6164 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6164 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 308
background.js:6171 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM: false
background.js:6171 NTLMSSP_REQUEST_TARGET: true
background.js:6171 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6171 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6171 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6171 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6171 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6171 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6171 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6171 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6171 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6171 NTLMSSP_NEGOTIATE_128: true
background.js:6171 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6171 NTLMSSP_NEGOTIATE_56: false
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 422}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 92
background.js:6157 Client#getSharedResourceList
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 96}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 35
background.js:11846 3221225506: NT_STATUS_ACCESS_DENIED

**Comment by hvdwolf** [comment]
I also have a Debian linux server which I use as webserver and which currently only has NFS shares.
I quickly setup a samba share and connected.
That works! 
Unfortunately, as described above, I still can't connect to my NAS.

**Comment by hvdwolf** [comment]
Hi,

Some observations.
My NAS has a public share, 2 multi-user shares and 1 specific configuration share.
If I specifiy the ip-address without username and password, I get the popup and option to connect to all 4 shares. Of course I can only connect to the Public share in this case (But this is already a great step forward :) ).
As soon as I specify a username and password I get the errors.
Is it possible to provide a share name as well?
I understand that you want to keep it as simple as possible, but if you would be able to specify a share could that solve this issue? Possibly via a checkbox setting like "Specify share name"?

**Comment by AndreyLavrov** [comment]
SMB ver. 1.1.8 have solved the issue!
Now I can mount SMB shares on Windows 7 (Standalone) and Windows 2008 R2 (Member).
Files.app is not showing any error now.

**Comment by yoichiro** [comment]
@AndreyLavrov Good. Thank you for the reporting.
