### ISSUE TITLE
Can't connect to server with mixed SMB shares authorizations

### ISSUE THREAD

**Issue by hvdwolf** [yoichiro/chromeos-filesystem-cifs#40]
As AndreyLavrov unfortunately closed issue https://github.com/yoichiro/chromeos-filesystem-cifs/issues/32, I open another one.

Please have a look at my 3 last posts in that issue 32 issue.

Edit: Never mind. I copy them here below.
# 

Hi, I just checked with your 1.1.8 version.

Unfortunately it still doesn't work. See below. I removed the password.

Object {type: "getSharedResources", serverName: "192.168.144.140", serverPort: "445", username: "pohd", password: "xxxxxx"}
background.js:6157 Client#login
background.js:6157 connect
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 127
background.js:6171 CAP_EXTENDED_SECURITY: true
background.js:6171 CAP_COMPRESSED_DATA: false
background.js:6171 CAP_BULK_TRANSFER: false
background.js:6171 CAP_UNIX: true
background.js:6171 CAP_LARGE_WRITEX: true
background.js:6171 CAP_LARGE_READX: true
background.js:6171 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6171 CAP_DFS: true
background.js:6171 CAP_NT_FIND: true
background.js:6171 CAP_LOCK_AND_READ: true
background.js:6171 CAP_LEVEL_II_OPLOCKS: true
background.js:6171 CAP_STATUS32: true
background.js:6171 CAP_RPC_REMOTE_APIS: true
background.js:6171 CAP_NT_SMBS: true
background.js:6171 CAP_LARGE_FILES: true
background.js:6171 CAP_UNICODE: true
background.js:6171 CAP_MPX_MODE: false
background.js:6171 CAP_RAW_MODE: true
background.js:6164 Header {types: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6164 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6164 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 308
background.js:6171 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM: false
background.js:6171 NTLMSSP_REQUEST_TARGET: true
background.js:6171 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6171 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6171 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6171 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6171 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6171 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6171 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6171 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6171 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6171 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6171 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6171 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6171 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6171 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6171 NTLMSSP_NEGOTIATE_128: true
background.js:6171 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6171 NTLMSSP_NEGOTIATE_56: false
background.js:6164 Packet {types: Types, data_: ArrayBuffer, dataLength_: 422}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 92
background.js:6157 Client#getSharedResourceList
background.js:6164 Packet {types: Types, data_: ArrayBuffer, dataLength_: 96}
background.js:6157 writePacket
background.js:6157 readPacket
background.js:6157 _readPacketSize
background.js:6157 _readPacketSize - 2
background.js:6157 readPacket: 35
background.js:11846 3221225506: NT_STATUS_ACCESS_DENIED
# 

hvdwolf commented 5 hours ago
I also have a Debian linux server which I use as webserver and which currently only has NFS shares.
I quickly setup a samba share and connected.
That works! 
Unfortunately, as described above, I still can't connect to my NAS.
# 

hvdwolf commented 2 hours ago
Hi,

Some observations.
My NAS has a public share, 2 multi-user shares and 1 specific configuration share.
If I specifiy the ip-address without username and password, I get the popup and option to connect to all 4 shares. Of course I can only connect to the Public share in this case (But this is already a great step forward :) ).
As soon as I specify a username and password I get the errors.
Is it possible to provide a share name as well?
I understand that you want to keep it as simple as possible, but if you would be able to specify a share could that solve this issue? Possibly via a checkbox setting like "Specify share name"?

**Comment by yoichiro** [comment]
@hvdwolf I can't know the reason of "NT_STATUS_ACCESS_DENIED". As the error name, you rejected to connect from your server. You should check the server log of your server.

**Comment by hvdwolf** [comment]
Below my smbd.log. All the preallocate errors are from the startup or restart of nmbd/smbd

There are several authentication methods for samba which are set in the smb.conf
I had:
auth methods = guest, sam_ignoredomain, winbind:ntdomain

I changed that to:
auth methods = guest, sam_ignoredomain, winbind:ntdomain, ntdomain

Look at line "2015/06/07 16:02:25,  0".  If there is no domain, it can't be used.  

So I removed that again and restarted it. I get the NT_STATUS_LOGON_FAILURE again, but nothing is written to the log..

cat log.smbd
[2015/06/07 16:02:06,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:02:06,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:02:06,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:02:06,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:02:06,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:02:06,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:02:06,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:02:06,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:02:25,  0] source/auth/auth_domain.c:check_ntdomain_security(319)
  check_ntdomain_security: Configuration error!  Cannot use ntdomain auth method when not a member of a domain.
[2015/06/07 16:03:18,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:03:18,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:03:18,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:03:18,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:03:18,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:03:18,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"
[2015/06/07 16:03:18,  1] source/param/loadparm.c:map_parameter(6090)
  Unknown parameter encountered: "preallocate"
[2015/06/07 16:03:18,  0] source/param/loadparm.c:lp_do_parameter(7176)
  Ignoring unknown parameter "preallocate"

My security is set to "security = user", which is the default for samba. Setting it to share or domain gives other errors but does not solve it.

**Comment by yoichiro** [comment]
@hvdwolf I have already released the version including supporting "share" mode and etc. Could you confirm whether you can reproduce this issue with the latest version?

**Comment by hvdwolf** [comment]
Hi, I'm sorry. I completely missed the mail notification.

It works fine now. No matter whether I configure my server for "security = share" (deprecated) or "security = user" (default), I can connect.

**Comment by hvdwolf** [comment]
However, looking back at the the title of my issue: The mixed shares still don't work.
If I connect only on ip address (and port), the SMB app shows all available shares but I can only connect to the public ones.
When I add my username/password (for the protected shares) I still get the NT_STATUS_LOGON_FAILURE

**Comment by hvdwolf** [comment]
I can now mount both my user/password protected shares as well as my public shares. Very nice.
