### ISSUE TITLE
Cannot connect to Mac running Windows File Sharing

### ISSUE THREAD

**Issue by nikjft** [yoichiro/chromeos-filesystem-cifs#42]
I cannot connect from Chromebook to Mac with Windows File Sharing (Samba) turned on. I get a not-authorized error, number 3221225506.

Running MacOS X version 10.6.8, smbd version "3.0.28a-apple".

Connections from Windows work fine, as do connections from ES File Explorer on Android - so I know the login and password is correct.
## smbd server log from Mac:

[2015/06/06 21:36:42, 0, pid=43938] /SourceCache/samba/samba-235.9/samba/source/lib/opendirectory.c:get_opendirectory_authenticator(247)
  failed to read DomainAdmin credentials, err=67 fd=19 errno=2
  [2015/06/06 21:36:42, 0, pid=43938] /SourceCache/samba/samba-235.9/samba/source/passdb/pdb_odsam.c:odssam_getsampwnam(1576)
  opendirectory_sam_searchname gave -14136 [eDSRecordNotFound]: no dsRecTypeStandard:Users record for account 'admin'
  [2015/06/06 21:36:42, 1, pid=43938] /SourceCache/samba/samba-235.9/samba/source/smbd/service.c:make_connection(1174)
  make_connection: refusing to connect with no session setup
## Background page log:

Object {type: "getSharedResources", serverName: "10.20.30.44", serverPort: "445", username: "*****_", password: "**_***"}
Client#login
connect
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 254
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: true
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 252
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 358}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 114
Client#getSharedResourceList
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 88}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 35
3221225506: NT_STATUS_ACCESS_DENIED

**Comment by AndreyLavrov** [comment]
SMB/CIFS does not support domain credentials yet.
Are you sure that you do not use "admin" account from your domain instead of a local account?
Please, create a dedicated local account on your Mac for testing purposes.

**Comment by yoichiro** [comment]
@nikjft Is this issue reproduced with the latest version? I already modified many logics...

**Comment by nikjft** [comment]
Same result with latest version from chrome store.

**Comment by yoichiro** [comment]
@nikjft Could you give me the background page log when you use the latest version?

**Comment by nikjft** [comment]
Background page:

Object {type: "getSharedResources", serverName: "10.20.30.44", serverPort: "445", username: "user", password: "password"}
Client#login
Domain name not specified. '?' will be applied.
connect
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 254
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: true
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 252
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 358}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 114
Client#getSharedResourceList
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 88}
writePacket
readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 35
3221225506: NT_STATUS_ACCESS_DENIED

smbd server log:

[2015/06/16 17:41:35, 0, pid=75140] /SourceCache/samba/samba-235.9/samba/source/lib/opendirectory.c:get_opendirectory_authenticator(247)
  failed to read DomainAdmin credentials, err=67 fd=19 errno=2
[2015/06/16 17:41:36, 0, pid=75140] /SourceCache/samba/samba-235.9/samba/source/passdb/pdb_odsam.c:odssam_getsampwnam(1576)
  opendirectory_sam_searchname gave -14136 [eDSRecordNotFound]: no dsRecTypeStandard:Users record for account 'admin'
[2015/06/16 17:41:36, 1, pid=75140] /SourceCache/samba/samba-235.9/samba/source/smbd/service.c:make_connection(1174)
  make_connection: refusing to connect with no session setup

**Comment by nikjft** [comment]
This remains a problem on latest version. Any idea on how to fix/work-around?

**Comment by yoichiro** [comment]
@nikjft I just released a new version 2.1.1 including SMB2 support. Could you confirm whether this issue is reproduced or not?

**Comment by nikjft** [comment]
Yoichiro, I'm afraid it's still not working. I also tried connecting to a Mac with the latest version of MacOS X with SMB sharing active and it won't connect to that, either. It does successfully browse available servers and identify those with sharing enabled, so I know it's not just a network problem. I can also connect successfully from Mac and Windows machines using SMB/CIFS networking. Very strange. In case it's helpful, I turned on full log level and captured the background page log again. Here's what I got:

```
Object {type: "lookupServiceList"}
Object {serverName: "10.20.30.44", serverPort: "445", username: "nik", password: "xxxxx", domainName: ""…}
Client#login
Domain name not specified. '?' will be applied.
connect
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
writePacket
FF53 4D42 7200 0000 0018 03C8 0000 0000  .SMBr...........
0000 0000 0000 0000 0000 0700 0000 0100  ................
0017 0002 4E54 204C 4D20 302E 3132 0002  ....NT LM 0.12..
534D 4220 322E 3030 3200  SMB 2.002.

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 254
FF53 4D42 7200 0000 0088 01C8 0000 0000  .SMBr...........
0000 0000 0000 0000 0000 0700 0000 0100  ................
1100 0003 3200 0100 0000 0200 0000 0100  ....2...........
EE78 0100 FDF3 8080 006C 6DA5 F7F2 D001  .x.......lm.....
6801 00B9 006B 7562 7269 6B00 0000 0000  h....kubrik.....
0000 0000 0060 81A6 0606 2B06 0105 0502  .....`....+.....
A081 9B30 8198 A024 3022 0609 2A86 4886  ...0...$0"..*.H.
F712 0102 0206 092A 8648 82F7 1201 0202  .......*.H......
060A 2B06 0104 0182 3702 020A A370 306E  ..+.....7....p0n
A06C 1B6A 6369 6673 2F4C 4B44 433A 5348  .l.jcifs/LKDC:SH
4131 2E33 4341 3537 3646 3335 4436 3038  A1.3CA576F35D608
3139 3042 4430 4335 3944 4441 3638 3236  190BD0C59DDA6826
3243 4436 3431 3844 4233 4640 4C4B 4443  2CD6418DB3F@LKDC
3A53 4841 312E 3343 4135 3736 4633 3544  :SHA1.3CA576F35D
3630 3831 3930 4244 3043 3539 4444 4136  608190BD0C59DDA6
3832 3632 4344 3634 3138 4442 3346  8262CD6418DB3F

Negotiated with SMB1/CIFS
CAP_EXTENDED_SECURITY: true
CAP_COMPRESSED_DATA: false
CAP_BULK_TRANSFER: false
CAP_UNIX: true
CAP_LARGE_WRITEX: true
CAP_LARGE_READX: true
CAP_INFOLEVEL_PASSTHROUGH: true
CAP_DFS: true
CAP_NT_FIND: true
CAP_LOCK_AND_READ: true
CAP_LEVEL_II_OPLOCKS: true
CAP_STATUS32: true
CAP_RPC_REMOTE_APIS: true
CAP_NT_SMBS: true
CAP_LARGE_FILES: true
CAP_UNICODE: true
CAP_MPX_MODE: false
CAP_RAW_MODE: true
NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
NEGOTIATE_SECURITY_USER_LEVEL: 1
Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 131072, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 96494…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160, packetHelper_: PacketHelper}
writePacket
FF53 4D42 7300 0000 0018 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 0000 0200  ................
0CFF 0000 0000 0032 0001 00EE 7801 0029  .......2....x..)
0000 0000 0054 0000 8065 004E 544C 4D53  .....T...e.NTLMS
5350 0001 0000 0005 3208 2001 0001 0020  SP......2. ....
0000 0008 0008 0021 0000 003F 4653 505F  .......!...?FSP_
4349 4653 4300 6800 7200 6F00 6D00 6500  CIFSC.h.r.o.m.e.
4F00 5300 0000 4600 6900 6C00 6500 2000  O.S...F.i.l.e. .
5300 7900 7300 7400 6500 6D00 2000 6600  S.y.s.t.e.m. .f.
6F00 7200 2000 4300 4900 4600 5300 0000  o.r. .C.I.F.S...

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 252
FF53 4D42 7316 0000 C088 01C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 6400 0200  ............d...
04FF 0000 0000 008A 00D1 004E 544C 4D53  ...........NTLMS
5350 0002 0000 000C 000C 0030 0000 0005  SP.........0....
028A 2001 D76E 9BB9 3141 4100 0000 0000  .. ..n..1AA.....
0000 004E 004E 003C 0000 004B 0055 0042  ...N.N.<...K.U.B
0052 0049 004B 0002 000C 004B 0055 0042  .R.I.K.....K.U.B
0052 0049 004B 0001 000C 004B 0055 0042  .R.I.K.....K.U.B
0052 0049 004B 0004 000A 006C 006F 0063  .R.I.K.....l.o.c
0061 006C 0003 0018 006B 0075 0062 0072  .a.l.....k.u.b.r
0069 006B 002E 006C 006F 0063 0061 006C  .i.k...l.o.c.a.l
0000 0000 0000 5500 6E00 6900 7800 0000  ......U.n.i.x...
5300 6100 6D00 6200 6100 2000 3300 2E00  S.a.m.b.a. .3...
3000 2E00 3200 3800 6100 2D00 6100 7000  0...2.8.a.-.a.p.
7000 6C00 6500 0000 5700 4F00 5200 4B00  p.l.e...W.O.R.K.
4700 5200 4F00 5500 5000 0000  G.R.O.U.P...

Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
NTLMSSP_NEGOTIATE_UNICODE: true
NTLMSSP_NEGOTIATE_OEM: false
NTLMSSP_REQUEST_TARGET: true
NTLMSSP_NEGOTIATE_SIGN: false
NTLMSSP_NEGOTIATE_SEAL: false
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
NTLMSSP_NEGOTIATE_LM_KEY: false
NTLMSSP_NEGOTIATE_NETWARE: false
NTLMSSP_NEGOTIATE_NTLM: true
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
NTLMSSP_NEGOTIATE_LOCAL_CALL: false
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
NTLMSSP_TARGET_TYPE_DOMAIN: false
NTLMSSP_TARGET_TYPE_SERVER: true
NTLMSSP_TARGET_TYPE_SHARE: false
NTLMSSP_NEGOTIATE_NTLM2: true
NTLMSSP_REQUEST_INIT_RESPONSE: false
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
NTLMSSP_NEGOTIATE_TARGET_INFO: true
NTLMSSP_NEGOTIATE_128: true
NTLMSSP_NEGOTIATE_KEY_EXCH: false
NTLMSSP_NEGOTIATE_56: false
Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
SessionSetupAndxRequest {types_: Types, maxBufferSize_: 131072, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 96494…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 358, packetHelper_: PacketHelper}
writePacket
FF53 4D42 7300 0000 0018 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 6400 0300  ............d...
0CFF 0000 0000 0032 0001 00EE 7801 00EE  .......2....x...
0000 0000 0054 0000 802B 014E 544C 4D53  .....T...+.NTLMS
5350 0003 0000 0018 0018 0040 0000 007E  SP.........@...~
007E 0058 0000 0002 0002 00D6 0000 0006  .~.X............
0006 00D8 0000 0010 0010 00DE 0000 0000  ................
0000 0000 0000 0001 0008 0028 E289 8623  ...........(...#
AA9F 7BF8 6D99 22E4 5662 0EC1 0D87 D5E6  ..{.m.".Vb......
A148 63EF 2092 0BEA 11DA 6665 6B5C FA7E  .Hc. .....fek\.~
EE28 5401 0100 0000 0000 0040 B0CF A5F7  .(T........@....
F2D0 0170 DCE5 B048 0000 0000 0000 0002  ...p...H........
000C 004B 0055 0042 0052 0049 004B 0001  ...K.U.B.R.I.K..
000C 004B 0055 0042 0052 0049 004B 0004  ...K.U.B.R.I.K..
000A 006C 006F 0063 0061 006C 0003 0018  ...l.o.c.a.l....
006B 0075 0062 0072 0069 006B 002E 006C  .k.u.b.r.i.k...l
006F 0063 0061 006C 0000 0000 0000 0000  .o.c.a.l........
003F 006E 0069 006B 0046 0053 0050 005F  .?.n.i.k.F.S.P._
0043 0049 0046 0053 0000 4300 6800 7200  .C.I.F.S..C.h.r.
6F00 6D00 6500 4F00 5300 0000 4600 6900  o.m.e.O.S...F.i.
6C00 6500 2000 5300 7900 7300 7400 6500  l.e. .S.y.s.t.e.
6D00 2000 6600 6F00 7200 2000 4300 4900  m. .f.o.r. .C.I.
4600 5300 0000  F.S...

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 114
FF53 4D42 7300 0000 0088 01C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 6500 0300  ............e...
04FF 0000 0000 0000 0047 0000 5500 6E00  .........G..U.n.
6900 7800 0000 5300 6100 6D00 6200 6100  i.x...S.a.m.b.a.
2000 3300 2E00 3000 2E00 3200 3800 6100   .3...0...2.8.a.
2D00 6100 7000 7000 6C00 6500 0000 5700  -.a.p.p.l.e...W.
4F00 5200 4B00 4700 5200 4F00 5500 5000  O.R.K.G.R.O.U.P.
0000  ..

Client#connectSharedResource
Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
TreeConnectAndxRequest {types_: Types, path_: "\\10.20.30.44\FRIETEB DATA", service_: "?????"}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 104, packetHelper_: PacketHelper}
writePacket
FF53 4D42 7500 0000 0018 03C8 0000 0000  .SMBu...........
0000 0000 0000 0000 0000 0700 6400 0400  ............d...
04FF 0000 0000 0001 003D 0000 5C00 5C00  .........=..\.\.
3100 3000 2E00 3200 3000 2E00 3300 3000  1.0...2.0...3.0.
2E00 3400 3400 5C00 4600 5200 4900 4500  ..4.4.\.F.R.I.E.
5400 4500 4200 2000 4400 4100 5400 4100  T.E.B. .D.A.T.A.
0000 3F3F 3F3F 3F00  ..?????.

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 35
FF53 4D42 7522 0000 C088 01C8 0000 0000  .SMBu"..........
0000 0000 0000 0000 0000 0700 6400 0400  ............d...
0000 00 ...
```

**Comment by yoichiro** [comment]
@nikjft Thank you for the log. I found a problem about User ID described at the following: https://github.com/yoichiro/chromeos-filesystem-cifs/issues/109#issuecomment-147560322

**Comment by yoichiro** [comment]
@nikjft I have just released a new version 2.3.1. This version includes the modification about User ID problem. Could you test the version on your environment?

**Comment by nikjft** [comment]
Success! It works perfectly. Server browsing is trouble free, and I can
copy and open files directly from the SMB share.

Thanks so very much for your hard work on this. This was the final missing
component from my ChromeBook. Now I can back up, access, and share files
with people on my LAN without any trouble.

--Nik

**Comment by yoichiro** [comment]
@nikjft My pleasure. I close this issue. Thank you for the feedback!
