### ISSUE TITLE
Unable to cope with sleeping NAS

### ISSUE THREAD

**Issue by dnikkel** [yoichiro/chromeos-filesystem-cifs#43]
I'm sure if this is as issue with the SMB provider, or somewhere else.  My Synology NAS spins down after a certain period of inactivity.  On Windows and OSX, the OS deals gracefully with this situation, waiting will the NAS spins up and establishing the connection.  Later, if it spins down due to inactivity, it will spin back up when an attempt is made to access the share.  Neither of these operations seems to work as expected on Chrome OS with the SMB provider.  You will get a stream of error messages on the console along these lines...

getTaskQueue: Created. cifsfs://192.168.1.229:445/dave/Music
background.js:13469 getTaskQueue: Created. cifsfs://192.168.1.229:445/dave/Pictures
background.js:13469 getTaskQueue: Created. cifsfs://192.168.1.229:445/dave/home
background.js:12699 TaskQueue: addTask - Call consume task: length=3
background.js:12709 TaskQueue: consumeTask - execute task: length=3
background.js:12871 resume - start
background.js:12699 TaskQueue: addTask - Call consume task: length=3
background.js:12709 TaskQueue: consumeTask - execute task: length=3
background.js:12871 resume - start
background.js:12699 TaskQueue: addTask - Call consume task: length=3
background.js:12709 TaskQueue: consumeTask - execute task: length=3
background.js:12871 resume - start
background.js:13520 net::ERR_INTERNET_DISCONNECTED
background.js:13336 resume failed: net::ERR_INTERNET_DISCONNECTED
background.js:13520 net::ERR_INTERNET_DISCONNECTED
background.js:13336 resume failed: net::ERR_INTERNET_DISCONNECTED
background.js:13520 net::ERR_INTERNET_DISCONNECTED
background.js:13336 resume failed: net::ERR_INTERNET_DISCONNECTED
3background.js:13253 _doUnmount

or this...

Object {entryPath: "/", fileSystemId: "cifsfs://192.168.1.229:445/dave/Music", requestId: 1631, thumbnail: false}
background.js:12758 TaskQueue: addTask - Call consume task: length=1
background.js:12768 TaskQueue: consumeTask - execute task: length=1
background.js:12987 onGetMetadataRequested: thumbnail=false
background.js:12988 Object {entryPath: "/", fileSystemId: "cifsfs://192.168.1.229:445/dave/Pictures", requestId: 119, thumbnail: false}
background.js:12758 TaskQueue: addTask - Call consume task: length=1
background.js:12768 TaskQueue: consumeTask - execute task: length=1
background.js:12987 onGetMetadataRequested: thumbnail=false
background.js:12988 Object {entryPath: "/", fileSystemId: "cifsfs://192.168.1.229:445/dave/home", requestId: 158, thumbnail: false}
background.js:11439 Error: writeInfo.resultCode=-15
background.js:13007 Sending data failed: -15
background.js:13579 Sending data failed: -15
background.js:13512 Object {message: "net::ERR_SOCKET_NOT_CONNECTED"}
background.js:12775 TaskQueue: consumeTask - queue: empty
background.js:11439 Error: writeInfo.resultCode=-15
background.js:13007 Sending data failed: -15
background.js:13579 Sending data failed: -15
background.js:13512 Object {message: "net::ERR_SOCKET_NOT_CONNECTED"}
background.js:12775 TaskQueue: consumeTask - queue: empty
background.js:11439 Error: writeInfo.resultCode=-15
background.js:13007 Sending data failed: -15
background.js:13579 Sending data failed: -15
background.js:13512 Object {message: "net::ERR_SOCKET_NOT_CONNECTED"}
background.js:12775 TaskQueue: consumeTask - queue: empty

The remedy is pretty painful - I need to go to a different computer (Windows or OSX in my case) to wake up the NAS.  But that is not sufficient - I also need to reboot the Chromebox before it will remount the shares.  In other words, if I only had Chrome OS devices, I would have no way of waking up a sleeping NAS.

**Comment by yoichiro** [comment]
@dnikkel I could reproduce this issue. I intend to add the re-connect logic. The diff has already created at #47, and it will be released at the next version.

**Comment by yoichiro** [comment]
@dnikkel The new version 1.1.9 has been released. Could you confirm whether this issue is fixed or not by using 1.1.9?

**Comment by dnikkel** [comment]
With 1.1.9, I'm still having the shares disconnected.  This is what I see in the log now:

background.js:6175 net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175
background.js:6176 console.trace()Debug.error @ background.js:6176
background.js:6175 resume failed: net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175
background.js:6176 console.trace()Debug.error @ background.js:6176
background.js:6175 net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175
background.js:6176 console.trace()Debug.error @ background.js:6176
background.js:6175 resume failed: net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175
background.js:6176 console.trace()Debug.error @ background.js:6176
background.js:6175 net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175
background.js:6176 console.trace()Debug.error @ background.js:6176
background.js:6175 resume failed: net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175
background.js:6176 console.trace()Debug.error @ background.js:6176
3background.js:6157 _doUnmount
background.js:6157 cifsfs://192.168.1.229:445/dave/Music
background.js:6157 cifsfs://192.168.1.229:445/dave/Pictures
background.js:6157 cifsfs://192.168.1.229:445/dave/home
background.js:6157 writePacket
background.js:6157 deleteTaskQueue: cifsfs://192.168.1.229:445/dave/Music
background.js:6157 deleteMetadataCache: cifsfs://192.168.1.229:445/dave/Music
background.js:6157 writePacket
background.js:6157 deleteTaskQueue: cifsfs://192.168.1.229:445/dave/Pictures
background.js:6157 deleteMetadataCache: cifsfs://192.168.1.229:445/dave/Pictures
background.js:6157 writePacket
background.js:6157 deleteTaskQueue: cifsfs://192.168.1.229:445/dave/home
background.js:6157 deleteMetadataCache: cifsfs://192.168.1.229:445/dave/home
3extensions::lastError:133 Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedError: NOT_FOUND
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13460:41)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13379:25)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13387:29)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13763:21)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11831:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12791:13)

**Comment by yoichiro** [comment]
@dnikkel Was the connection actually disconnected?

**Comment by dnikkel** [comment]
As far as I can tell, the network connection was fine.  I think every time I've had trouble after the NAS has spun down, I always see the internet disconnected error.  I do believe the situation has changed with 1.1.9.  My shares are no longer being dismounted as a result of the NAS being asleep.  However, it still seems unable to continue once the NAS has spun back up.  Last night, I did not shut down my Chromebox and when I sent to use it today, I had a network 100 error and I was unable to even open the file manager app, it's like file services were completely frozen.  In the log, I was seeing messages like the following:

Network error occurred: -100
Debug.error @ background.js:6175
(anonymous function) @ background.js:13479
(anonymous function) @ background.js:13755
(anonymous function) @ background.js:11814
(anonymous function) @ background.js:12182
ChromeSocket2.raiseError @ background.js:11528
ChromeSocket2.onReceiveError @ background.js:11522
(anonymous function) @ background.js:11507
target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:395
target.(anonymous function) @ extensions::SafeBuiltins:19
publicClass.(anonymous function) @ extensions::utils:94
EventImpl.dispatch_ @ extensions::event_bindings:379
dispatchArgs @ extensions::event_bindings:247
dispatchEvent @ extensions::event_bindings:256

These are definitely different than the pre-1.1.9 log entries.

**Comment by dnikkel** [comment]
I also meant to add, I had to reboot the Chromebox to file services to respond again.

**Comment by yoichiro** [comment]
@dnikkel I have just released the new version 1.2.0. In this version, I modified the re-connecting logic. Could you confirm whether this issue is reproduced or not with 1.2.0 on your environment?

**Comment by dnikkel** [comment]
I'm seeing change again with 1.2.0.  I still get similar errors when the NAS spins down, but I no longer have to reboot my Chromebox to be able to remount the shares.  Here's what I have in my log now...

resume - start
background.js:6157 Client#login
background.js:6171 Domain name not specified. '?' will be applied.
background.js:6157 connect
background.js:6157 Client#login
background.js:6171 Domain name not specified. '?' will be applied.
background.js:6157 connect
background.js:6157 getMetadataCache: Created. cifsfs://192.168.1.229:445/undefined@dave/Music
background.js:6157 Client#login
background.js:6171 Domain name not specified. '?' will be applied.
background.js:6157 connect
background.js:6157 getMetadataCache: Created. cifsfs://192.168.1.229:445/undefined@dave/Pictures
background.js:6157 getMetadataCache: Created. cifsfs://192.168.1.229:445/undefined@dave/home
background.js:6175 net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175handleError @ background.js:13667(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6176 console.trace()Debug.error @ background.js:6176handleError @ background.js:13667(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6175 resume failed: net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175(anonymous function) @ background.js:13462handleError @ background.js:13676(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6176 console.trace()Debug.error @ background.js:6176(anonymous function) @ background.js:13462handleError @ background.js:13676(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6175 net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175handleError @ background.js:13667(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6176 console.trace()Debug.error @ background.js:6176handleError @ background.js:13667(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6175 resume failed: net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175(anonymous function) @ background.js:13462handleError @ background.js:13676(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6176 console.trace()Debug.error @ background.js:6176(anonymous function) @ background.js:13462handleError @ background.js:13676(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6175 net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175handleError @ background.js:13667(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6176 console.trace()Debug.error @ background.js:6176handleError @ background.js:13667(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6175 resume failed: net::ERR_INTERNET_DISCONNECTEDDebug.error @ background.js:6175(anonymous function) @ background.js:13462handleError @ background.js:13676(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
background.js:6176 console.trace()Debug.error @ background.js:6176(anonymous function) @ background.js:13462handleError @ background.js:13676(anonymous function) @ background.js:13006(anonymous function) @ background.js:13786(anonymous function) @ background.js:11814(anonymous function) @ background.js:12151(anonymous function) @ background.js:11310(anonymous function) @ background.js:11601target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
3background.js:6157 _doUnmount
background.js:6157 cifsfs://192.168.1.229:445/undefined@dave/Music
background.js:6157 cifsfs://192.168.1.229:445/undefined@dave/Pictures
background.js:6157 cifsfs://192.168.1.229:445/undefined@dave/home
background.js:6157 writePacket
background.js:6157 deleteTaskQueue: cifsfs://192.168.1.229:445/undefined@dave/Music
background.js:6157 deleteMetadataCache: cifsfs://192.168.1.229:445/undefined@dave/Music
background.js:6157 writePacket
background.js:6157 deleteTaskQueue: cifsfs://192.168.1.229:445/undefined@dave/Pictures
background.js:6157 deleteMetadataCache: cifsfs://192.168.1.229:445/undefined@dave/Pictures
background.js:6157 writePacket
background.js:6157 deleteTaskQueue: cifsfs://192.168.1.229:445/undefined@dave/home
background.js:6157 deleteMetadataCache: cifsfs://192.168.1.229:445/undefined@dave/home
3extensions::lastError:133 Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedError: NOT_FOUND
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13474:41)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13391:25)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13399:29)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13794:21)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11836:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12796:13)

**Comment by yoichiro** [comment]
@dnikkel At least, I think that it is difficult to continue to do all operations, if your server is down... I don't know any solutions... I hope that you should change settings of your server. Sorry.
