### ISSUE TITLE
How to connect to a specific share like \\server\share?

### ISSUE THREAD

**Issue by layerzerolabs** [yoichiro/chromeos-filesystem-cifs#62]
Hi,

I have a Linux box serving up Samba shares and I'm trying to connect to a share using the chrome extension (on a chromebook). There's nowhere to put the share name, just the server IP. This confuses me as in my experience (and in all the samba documentation) you have to specify a share. (i.e. \server\share). And since different shares have different logins I am stuck as to how to authenticate without specifying one.

Is the extension incompatible with this (standard) server configuration, or am I just confused?

Cheers

Naomi

**Comment by yoichiro** [comment]
@layerzerolabs The latest version has a feature to discovery servers which can talk the SMB Protocol. You can call the feature by clicking the rope icon on the bottom of left of the this app's screen. Could you use the feature? Then, I would like to hear your feedback.

**Comment by hvdwolf** [comment]
(It took me some time to find and find out that what you call the "rope icon" is actually the magnifying glass icon, or in other words: the find icon. :)
But how does this work? Both my servers are set to "browseable = yes" and they are not visible. My streamer on the other hand does not have a specific setting and is visible when clicking the magnifying glass icon. At the moment of using that function it only shows the server (my streamer), and when I select it it shows the several shares on that streamer/server.

**Comment by 0xR** [comment]
I have te same issue. Only my browsable folders are mountable. On windows it does work, I just have to enter the specific folder. When I view all the folders shared it is not visible. 

What this extention needs is another input field to manually set the share since it is not listed when you're browsing the share.

**Comment by jdsemma** [comment]
I have the same issue; my linux box has specific shares, and no way to specify them in the app. It doesn't show up when I click the search button at the bottom left (but a printer on our network does...)

**Comment by dblegend** [comment]
I have the same issue as well. Some of my personal shares have been set as intentionally invisible so that non power users on my network won't get confused by all the options.  I still need the ability to specify those shares directly for myself, however.  I haven't found a way to get to those using this tool at this time.

**Comment by yoichiro** [comment]
@layerzerolabs @hvdwolf @0xR @jdsemma @dblegend Yesterday, I have released a new version 1.5.0. This version has a textfield to enter a shared resource name you want to mount. If you want to mount a mount point which has a "browsable=no", try the field. I'm happy you feedback the feature to me.

**Comment by jdsemma** [comment]
Unfortunately still doesn't work. I continue to get NT_STATUS_ACCESS_DENIED. Under Windows, my mount is referenced as 192.168.39.1\jds.  (Internal IP, obviously.)  Under the Android app ES File Explorer, it is a forward slash instead. In all cases there is no domain name.

In the "shared resource name" field, I've tried "jds", "/jds", "\jds", "192.168.39.1/jds" and its backslash variant, all with the same error message. If I munge the password, it gives me NT_STATUS_LOGON_FAILURE, so it's definitely trying to connect, just can't connect to the right share.

**Comment by yoichiro** [comment]
@jdsemma Oh... I want to know a command which returned the ACCESS_DENIED. Could you check the debug log on the DevTools Console log?

**Comment by jdsemma** [comment]
At the risk of sounding dumb, any way to do that without being in DEV mode in the first place? (I glanced at the dev console under a chrome web window, but I'm accessing the SMB thingy via Files->Add New Service and nothing I do there pings the devtools console.)

**Comment by yoichiro** [comment]
@jdsemma See: https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by jdsemma** [comment]
2015-08-09 23:49:52.849 background.js:6176 Domain name not specified. '?' will be applied.
2015-08-09 23:49:52.879 background.js:6169 connect
2015-08-09 23:49:52.900 background.js:6169 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
2015-08-09 23:49:52.915 background.js:6169 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[1]}
2015-08-09 23:49:52.923 background.js:6169 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
2015-08-09 23:49:52.936 background.js:6176 CAP_EXTENDED_SECURITY: true
2015-08-09 23:49:52.945 background.js:6176 CAP_COMPRESSED_DATA: false
2015-08-09 23:49:52.959 background.js:6176 CAP_BULK_TRANSFER: false
2015-08-09 23:49:52.962 background.js:6176 CAP_UNIX: true
2015-08-09 23:49:52.966 background.js:6176 CAP_LARGE_WRITEX: true
2015-08-09 23:49:52.969 background.js:6176 CAP_LARGE_READX: true
2015-08-09 23:49:52.973 background.js:6176 CAP_INFOLEVEL_PASSTHROUGH: true
2015-08-09 23:49:52.988 background.js:6176 CAP_DFS: true
2015-08-09 23:49:52.992 background.js:6176 CAP_NT_FIND: true
2015-08-09 23:49:52.995 background.js:6176 CAP_LOCK_AND_READ: true
2015-08-09 23:49:52.998 background.js:6176 CAP_LEVEL_II_OPLOCKS: true
2015-08-09 23:49:53.002 background.js:6176 CAP_STATUS32: true
2015-08-09 23:49:53.006 background.js:6176 CAP_RPC_REMOTE_APIS: true
2015-08-09 23:49:53.020 background.js:6176 CAP_NT_SMBS: true
2015-08-09 23:49:53.024 background.js:6176 CAP_LARGE_FILES: true
2015-08-09 23:49:53.027 background.js:6176 CAP_UNICODE: true
2015-08-09 23:49:53.031 background.js:6176 CAP_MPX_MODE: false
2015-08-09 23:49:53.034 background.js:6176 CAP_RAW_MODE: true
2015-08-09 23:49:53.037 background.js:6176 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
2015-08-09 23:49:53.041 background.js:6176 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
2015-08-09 23:49:53.044 background.js:6176 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
2015-08-09 23:49:53.047 background.js:6176 NEGOTIATE_SECURITY_USER_LEVEL: 1
2015-08-09 23:49:53.062 background.js:6169 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
2015-08-09 23:49:53.066 background.js:6169 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
2015-08-09 23:49:53.072 background.js:6169 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
2015-08-09 23:49:53.077 background.js:6169 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 17925…}
2015-08-09 23:49:53.083 background.js:6169 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
2015-08-09 23:49:53.104 background.js:6169 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
2015-08-09 23:49:53.116 background.js:6176 NTLMSSP_NEGOTIATE_UNICODE: true
2015-08-09 23:49:53.119 background.js:6176 NTLMSSP_NEGOTIATE_OEM: false
2015-08-09 23:49:53.123 background.js:6176 NTLMSSP_REQUEST_TARGET: true
2015-08-09 23:49:53.126 background.js:6176 NTLMSSP_NEGOTIATE_SIGN: false
2015-08-09 23:49:53.129 background.js:6176 NTLMSSP_NEGOTIATE_SEAL: false
2015-08-09 23:49:53.134 background.js:6176 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
2015-08-09 23:49:53.137 background.js:6176 NTLMSSP_NEGOTIATE_LM_KEY: false
2015-08-09 23:49:53.140 background.js:6176 NTLMSSP_NEGOTIATE_NETWARE: false
2015-08-09 23:49:53.143 background.js:6176 NTLMSSP_NEGOTIATE_NTLM: true
2015-08-09 23:49:53.146 background.js:6176 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
2015-08-09 23:49:53.149 background.js:6176 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
2015-08-09 23:49:53.152 background.js:6176 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
2015-08-09 23:49:53.155 background.js:6176 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
2015-08-09 23:49:53.158 background.js:6176 NTLMSSP_TARGET_TYPE_DOMAIN: false
2015-08-09 23:49:53.161 background.js:6176 NTLMSSP_TARGET_TYPE_SERVER: true
2015-08-09 23:49:53.164 background.js:6176 NTLMSSP_TARGET_TYPE_SHARE: false
2015-08-09 23:49:53.167 background.js:6176 NTLMSSP_NEGOTIATE_NTLM2: true
2015-08-09 23:49:53.169 background.js:6176 NTLMSSP_REQUEST_INIT_RESPONSE: false
2015-08-09 23:49:53.173 background.js:6176 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
2015-08-09 23:49:53.175 background.js:6176 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
2015-08-09 23:49:53.178 background.js:6176 NTLMSSP_NEGOTIATE_TARGET_INFO: true
2015-08-09 23:49:53.181 background.js:6176 NTLMSSP_NEGOTIATE_128: true
2015-08-09 23:49:53.184 background.js:6176 NTLMSSP_NEGOTIATE_KEY_EXCH: false
2015-08-09 23:49:53.187 background.js:6176 NTLMSSP_NEGOTIATE_56: false
2015-08-09 23:49:53.223 background.js:6169 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
2015-08-09 23:49:53.227 background.js:6169 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 17925…}
2015-08-09 23:49:53.236 background.js:6169 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 350}
2015-08-09 23:49:53.262 background.js:6169 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
2015-08-09 23:49:53.291 background.js:6169 TreeConnectAndxRequest {types_: Types, path_: "\192.168.39.1\JDS", service_: "?????"}path_: "\192.168.39.1\JDS"service_: "?????"types_: Types__proto__: TreeConnectAndxRequest
2015-08-09 23:49:53.310 background.js:6169 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 88}

**Comment by dblegend** [comment]
Thanks for the new feature!  I was able to get it working for my various
hidden shares...  It's likely that I have them configured in some way that
is different from that of jdsemma.  I'll keep you updated if I run into any
other issues and am happy to help with troubleshooting however I can.

-Dave

**Comment by yoichiro** [comment]
@dblegend I'm happy you was able to mount your directory. Thank you for the report!

@jdsemma Thank you for the log. However, there is no ACCESS_DENIED. Could you find the ACCESS_DENIED error in your log on the console tab?

**Comment by jdsemma** [comment]
I cannot find ACCESS_DENIED anywhere. I've cleared the log, retried the connection, gotten the same result -- the log ends with "Packet", after the TreeConnectAndxRequest line.

**Comment by yoichiro** [comment]
@jdsemma Hmm... I guess that your server should record some errors about my app. Could you take a look some errors in your Samba server's log file? I cannot know the reason, because my app did output the error code only from your server...

**Comment by jdsemma** [comment]
The only line in my samba logfile is:

 [2015/08/10 17:24:02, 1] smbd/service.c:make_connection(1167)
  make_connection: refusing to connect with no session setup

**Comment by jdsemma** [comment]
One further bit of info that may be useful: I'm running samba v3.0.33-3.39.el5_8.

**Comment by yoichiro** [comment]
@jdsemma I found a bug regarding authentication. I have already released a new version 2.4.0 including code to fix the issue. See the following post for more detail: https://plus.google.com/u/0/+YoichiroTanaka/posts/EEJyicfnSqK

Could you confirm whether or not the new version works on your environment?

**Comment by jdsemma** [comment]
Successful connection! However I get "Some operations are taking longer
than expected. Do you want to abort them?" notification quite a lot, and it
seems to freeze (regardless of whether I abort or not.)

**Comment by jdsemma** [comment]
Successful connection! However I get "Some operations are taking longer
than expected. Do you want to

@jdsemma https://github.com/jdsemma I found a bug regarding
authentication. I have already released a new version 2.4.0 including code
to fix the issue. See the following post for more detail:
https://plus.google.com/u/0/+YoichiroTanaka/posts/EEJyicfnSqK

Could you confirm whether or not the new version works on your environment?

**Comment by yoichiro** [comment]
At least, @layerzerolabs didn't provide me more information. And, this issue has some different topics, Therefore, I close this issue. If you have a problem, you can register a new issue. Thank you for all feedbacks.
